### ISSUE TITLE
Update "staging" wp installation

### ISSUE THREAD

**Issue by tafkey** [EcvetStep/ecvet-cmf-toolkit#3]
Add the latest database (content) from the live website to the staging wordpress installation, at http://etk.eummena.org/

**Comment by tafkey** [comment]
@sale7salem I've pushed the code from the live site to a new github repo. You will also find the [sql dump there](https://github.com/EcvetStep/ecvet-step.eu/blob/master/ecvet_step.sql.gz). Can you try to git pull it and try to update your installation on the etk staging server?

**Comment by sale7salem** [comment]
The new version of wordpress is now on the stage server 
http://etk.eummena.org/ecvet-step.eu
