### ISSUE TITLE
Add link for returning to previous page

### ISSUE THREAD

**Issue by tafkey** [EcvetStep/ecvet-cmf-toolkit#7]
There are many pages where there's no way to go back to the previous one. For example: index.html#!/leveli3

**Comment by sale7salem** [comment]
Done
http://etk.eummena.org/cmf

**Comment by tafkey** [comment]
check also this page:
http://etk.eummena.org/cmf/index.html#!/page_About_More

**Comment by sale7salem** [comment]
Already added, but didn't updated on git.
I am finishing some interactions with users(comments, rating ...), then I'll update all once
