### ISSUE TITLE
HTML errors

### ISSUE THREAD

**Issue by tafkey** [EcvetStep/ecvet-cmf-toolkit#8]
In index.html
- [x] Line 80: a `ul` opens which contains no `li`s
- [x] Line 94: `href` cannot exist in `div`
- [x] Line 188, 189, 200, 201, 285, 598, 616,...: add `alt` for all images
- [x] Line 498: `level4` id already defined
- [x] Line 513: `level5` id already defined
- [x] Line 520: invalid `</p>`
- [x] Line 593: missing `</div>`

**Comment by sale7salem** [comment]
Resolved
