### ISSUE TITLE
"Live" staging version of the toolkit

### ISSUE THREAD

**Issue by tafkey** [EcvetStep/ecvet-cmf-toolkit#9]
We need to have an updated version of the toolkit online, so that for example Cleo can review the latest version of the content and functionality. 

At some place of the page there should be an indication of the **version** and / or **last update** date, even in the code if it's difficult to put it somewhere else.

**Comment by sale7salem** [comment]
I am updating our stage server every 24h
http://etk.eummena.org/cmf

**Comment by tafkey** [comment]
> Not Found
> 
> The requested URL /cmf was not found on this server.

**Comment by sale7salem** [comment]
try now
but its not the latest version, i'll upload the next version when finish all issues.

**Comment by sale7salem** [comment]
up-to-date
http://etk.eummena.org/cmf
